### ISSUE TITLE
ngToast.css のアニメーション設定で表示時に一瞬点滅します

### ISSUE THREAD

**Issue by ygoto3** [fusikky/perfect-ngToast#2]
デフォルト状態の `opacity` が設定されていないせいでしょうか。

![ngtoast](https://cloud.githubusercontent.com/assets/5054506/8200414/972ee84c-14ff-11e5-9d82-f231b80156ef.gif)

**Comment by fusikky** [comment]
defaultのcssにopacityを追加することで対応しました。

**Comment by ygoto3** [comment]
早々の対応ありがとうございます！
