### ISSUE TITLE
close() メソッド

### ISSUE THREAD

**Issue by ygoto3** [fusikky/perfect-ngToast#4]
ngDialog 同様に `ngToast.close()` で全てのトーストを消す機能と `ngToast.open()` で返るオブジェクトに `close(value)` メソッドが欲しいです。

**Comment by fusikky** [comment]
これら対応致しました。
https://github.com/fusikky/perfect-ngToast/commit/81fc7309cdee09394e601d2ef59fb086859cce6d
https://github.com/fusikky/perfect-ngToast/commit/a09cedf5b2f273b130e76bb44c45823b256b07f8
